name: Test and Build Image
on:
  push:

concurrency:
  group: test-and-build-sectory-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          elixir-version: 1.17.1
      - name: Get Deps
        run: |
          mix deps.get
      - name: Run Tests
        run: |
          cp -f .github/workflows/test.exs ./config/test.exs && mix test
      - name: Style Check
        run: |
          mix credo --all
  build-image:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Release and SBOM
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          ./.docker/production/build_release.sh
      - name: Compress SBOM
        run: |
          zip -er -P ${{ secrets.SBOM_PASSWORD }} sbom.zip sectory-alpine.sbom
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: SBOM
          path: sbom.zip